# Generated by Django 4.2.3 on 2023-07-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servico_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='facebook',
            field=models.CharField(default='#', max_length=100, verbose_name='Facebook'),
        ),
    ]
